table dimCalendar
	lineageTag: edf829a7-4045-4468-8975-dbf1c6631d7c

	measure Productivity = ```
			VAR positions =  SUM(fact_deliverypositions_lisa[Anzahl Positionen]) 
			VAR working_hours= SUM(fact_workingminuntes_all[MA_Stunden])
			VAR productivity = DIVIDE(positions, working_hours, 0)
			VAR ausreisser_cleaned = IF ( productivity > 1500, 0, productivity)
			RETURN ausreisser_cleaned
			```
		lineageTag: 9d04badd-bc15-4394-bfe0-347eb6deef20

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		formatString: General Date
		lineageTag: ac8ddd19-f547-4511-981a-ebcf38e989ca
		summarizeBy: none
		isNameInferred
		sourceColumn: [Date]

		variation Variation
			isDefault
			relationship: aeec6094-e2b3-47ff-8a74-584a4d165927
			defaultHierarchy: LocalDateTable_b0056958-5341-4a32-a314-b41782c67000.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition dimCalendar = calculated
		mode: import
		source = CALENDAR(DATE(2022,1,1), TODAY()-1)

	annotation PBI_Id = 146e363f265c4e36a8a16f50363b30bd

